/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import classes.Aleatorio;
import classes.TabuleiroComputador;
import classes.TabuleiroJogador;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author mayla
 */
public class Menu extends javax.swing.JFrame {
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setIconImage(new ImageIcon (getClass().getResource("/images/icon_batalhaNaval.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panMenu = new javax.swing.JPanel();
        btnMontarJogo = new javax.swing.JButton();
        btnJogoAleatorio = new javax.swing.JButton();
        lblBatalha = new javax.swing.JLabel();
        lblFundoMenu = new javax.swing.JLabel();
        panBarraTarefas = new javax.swing.JPanel();
        painelFerramentas = new javax.swing.JPanel();
        btnFechar = new javax.swing.JLabel();
        btnMinimizar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(getPreferredSize());
        setMinimumSize(getPreferredSize());
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setResizable(false);

        panMenu.setBackground(java.awt.Color.white);
        panMenu.setMaximumSize(getPreferredSize());
        panMenu.setMinimumSize(getPreferredSize());
        panMenu.setPreferredSize(getPreferredSize());
        panMenu.setLayout(null);

        btnMontarJogo.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        btnMontarJogo.setForeground(new java.awt.Color(1, 13, 58));
        btnMontarJogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_montar.png"))); // NOI18N
        btnMontarJogo.setText("Montar Jogo");
        btnMontarJogo.setFocusable(false);
        btnMontarJogo.setMaximumSize(getPreferredSize());
        btnMontarJogo.setMinimumSize(getPreferredSize());
        btnMontarJogo.setPreferredSize(new java.awt.Dimension(300, 80));
        btnMontarJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMontarJogoActionPerformed(evt);
            }
        });
        panMenu.add(btnMontarJogo);
        btnMontarJogo.setBounds(450, 506, 350, 100);

        btnJogoAleatorio.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        btnJogoAleatorio.setForeground(new java.awt.Color(1, 13, 58));
        btnJogoAleatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_aleatorio.png"))); // NOI18N
        btnJogoAleatorio.setText("Jogo Aleatorio");
        btnJogoAleatorio.setFocusable(false);
        btnJogoAleatorio.setMaximumSize(getPreferredSize());
        btnJogoAleatorio.setMinimumSize(getPreferredSize());
        btnJogoAleatorio.setPreferredSize(new java.awt.Dimension(300, 80));
        btnJogoAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogoAleatorioActionPerformed(evt);
            }
        });
        panMenu.add(btnJogoAleatorio);
        btnJogoAleatorio.setBounds(450, 364, 350, 100);

        lblBatalha.setFont(new java.awt.Font("SansSerif", 1, 150)); // NOI18N
        lblBatalha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBatalha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image_logo.png"))); // NOI18N
        lblBatalha.setPreferredSize(new java.awt.Dimension(30, 30));
        panMenu.add(lblBatalha);
        lblBatalha.setBounds(0, 90, 1200, 170);

        lblFundoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image_fundo_menu.png"))); // NOI18N
        lblFundoMenu.setText("jLabel2");
        lblFundoMenu.setPreferredSize(new java.awt.Dimension(1200, 700));
        panMenu.add(lblFundoMenu);
        lblFundoMenu.setBounds(0, 30, 1200, 700);

        panBarraTarefas.setBackground(new java.awt.Color(0, 0, 0));
        panBarraTarefas.setPreferredSize(new java.awt.Dimension(1200, 30));
        panBarraTarefas.setLayout(null);

        painelFerramentas.setBackground(new java.awt.Color(0, 0, 0));
        painelFerramentas.setPreferredSize(new java.awt.Dimension(97, 18));
        painelFerramentas.setLayout(null);

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_close_not_high.png"))); // NOI18N
        btnFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFecharMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFecharMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFecharMouseExited(evt);
            }
        });
        painelFerramentas.add(btnFechar);
        btnFechar.setBounds(52, 0, 45, 18);

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_min_not_high.png"))); // NOI18N
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseEntered(evt);
            }
        });
        painelFerramentas.add(btnMinimizar);
        btnMinimizar.setBounds(21, 0, 25, 18);

        panBarraTarefas.add(painelFerramentas);
        painelFerramentas.setBounds(1104, 0, 97, 18);

        panMenu.add(panBarraTarefas);
        panBarraTarefas.setBounds(0, 0, 1200, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnJogoAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogoAleatorioActionPerformed
        // TODO add your handling code here:
        TabuleiroJogador tabuleiroJogador = new TabuleiroJogador();
        TabuleiroComputador tabuleiroComputador = new TabuleiroComputador();
        tabuleiroJogador.setEtapaMontar(false);
        Jogo jogo = new Jogo(Aleatorio.gerarTabuleiro(tabuleiroJogador), Aleatorio.gerarTabuleiro(tabuleiroComputador));
        jogo.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnJogoAleatorioActionPerformed

    private void btnFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFecharMouseClicked
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog (null, "Gostaria mesmo de encerrar?","Fechar", dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnFecharMouseClicked

    private void btnFecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFecharMouseEntered
        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_close_high.png")));
    }//GEN-LAST:event_btnFecharMouseEntered

    private void btnFecharMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFecharMouseExited
        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_close_not_high.png")));
    }//GEN-LAST:event_btnFecharMouseExited

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void btnMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseEntered
        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_min_not_high.png")));
    }//GEN-LAST:event_btnMinimizarMouseEntered

    private void btnMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseExited
        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_min_high.png")));
    }//GEN-LAST:event_btnMinimizarMouseExited

    private void btnMontarJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMontarJogoActionPerformed
        // TODO add your handling code here:
        MontarTabuleiro montarTabuleiro = new MontarTabuleiro();
        montarTabuleiro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMontarJogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnFechar;
    private javax.swing.JButton btnJogoAleatorio;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JButton btnMontarJogo;
    private javax.swing.JLabel lblBatalha;
    private javax.swing.JLabel lblFundoMenu;
    private javax.swing.JPanel painelFerramentas;
    private javax.swing.JPanel panBarraTarefas;
    private javax.swing.JPanel panMenu;
    // End of variables declaration//GEN-END:variables
}
